### ISSUE TITLE
请问如何确定一个蓝牙设备支持哪种或哪些代理规范（Bluetoothprofile）呢

### ISSUE THREAD

**Issue by qustgah** [Joy-Whale/BluetoothProfile#1]

**Comment by qustgah** [comment]
在BluetoothClass中有doesClassMatch(int profile)，但是这个方法的用途，把我搞糊涂了，请问一下有什么思路吗，谢谢

**Comment by qustgah** [comment]
看源码，有这个android.bluetooth.BluetoothUuid，这个可以提供思路

**Comment by Joy-Whale** [comment]
那个是配对设备用的
